version: '2.2'
services:
  mytb:
    restart: always
    image: "postgis/postgis"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "blub"
    volumes:
      - postgis-data:/data
volumes:
  postgis-data:
